worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    upstream api_backend {
        server api:8000;
    }

    # Redireciona tráfego HTTP para HTTPS, exceto para o certbot
    server {
        listen 80;
        listen [::]:80;
        
        # SUBSTITUA '_; ' pelo seu domínio real, ex: server_name api.seudominio.com;
        server_name _; 

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            # Descomente a linha abaixo após gerar o certificado SSL com certbot
            # return 301 https://$host$request_uri;
            
            # Enquanto não houver SSL, mantém o proxy pass na porta 80:
            proxy_pass http://api_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # Bloco HTTPS (Descomente após gerar o certificado)
    # server {
    #     listen 443 ssl;
    #     listen [::]:443 ssl;
    #     
    #     # SUBSTITUA pelo seu domínio real, ex: server_name api.seudominio.com;
    #     server_name _; 
    #
    #     ssl_certificate /etc/letsencrypt/live/api.seudominio.com/fullchain.pem;
    #     ssl_certificate_key /etc/letsencrypt/live/api.seudominio.com/privkey.pem;
    #
    #     location / {
    #         proxy_pass http://api_backend;
    #         proxy_set_header Host $host;
    #         proxy_set_header X-Real-IP $remote_addr;
    #         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #         proxy_set_header X-Forwarded-Proto $scheme;
    #     }
    # }
}
